### ISSUE TITLE
Bug - Different strip color from 170th LED

### ISSUE THREAD

**Issue by Hokyjack** [ahodges9/LedFx#106]
Hello, thanks for amazing project.
I'm playing with this whole day, however I'm facing one strange bug - when using LedFx to control my 5m - 300px LED strip - it displays wrong colors from exactly 170th LED.
Example:
- if I set singleColor to RED - the first 170 leds are green and 171-300 leds are GREEN
- if I set singleColor to BLUE - the first 170 leds are green and 171-300 leds are RED
- if I set singleColor to GREEN - the first 170 leds are green and 171-300 leds are BLUE
- if I set singleColor to WHITE - the first 170 leds are green and 171-300 leds are (almost) RED
- if using any other effect (e.g. reactive) it also displays different colors after 170th led.

I use WLED as a firmware - when controlling leds via app it always displays correct colors for every effect.
I believe it is not a power issue - I'm using external PSU with up to 30A power supply.
The type of LEDs is WS2813, and I use ESP32 board.

![IMG_20200523_222806](https://user-images.githubusercontent.com/8573741/82740198-d67cdc00-9d46-11ea-8c9f-6e9c6e67e495.jpg)

Any hints what could be possibly wrong?
Thanks!
Jan

**Comment by Hokyjack** [comment]
Oh dang it! I just typed 170 into the repo code search and noticed,
I should had change the Universe Size to 510 as suggested 😄 

Anyway, maybe it would be a good idea, to change it automatically for user,
as he types in >170 in Pixel Count input field, or at least show some warning.

One more question. Sometimes I experience a very small lag when using reactive mode,
Is the e131 - WLED the best protocol to use? Or should I use UDP or something else?
Thanks.

**Comment by jterrell345** [comment]
I'm seeing this same issue too. Is there a fix coming?

**Comment by Mattallmighty** [comment]
Next release LedFx 0.8 should fix this: https://github.com/ahodges9/LedFx/pull/145
We have an auto add WLED devices on the LAN network feature on 0.8 I worked on. I have coded it for pixel = Universe Size automatically. 
Feel free to have a chat with the LedFx team on Discord: https://discord.com/invite/wJ755dY

**Comment by jterrell345** [comment]
This is still an issue. As you can see in this picture I have 3 long strips, One on the Upper peak and 2 along the side. They have green LEDs after the 170th. The dark spot in the middle is where LEDfx has the animations centered at on the strip.

It was recommended that I send in my yaml file so here it is in an attachment.

[yaml.zip](https://github.com/ahodges9/LedFx/files/5676553/yaml.zip)


![XmasLights](https://user-images.githubusercontent.com/60358518/101849391-36897300-3b1d-11eb-8d6e-03a23ccea86d.jpg)

**Comment by shauneccles** [comment]
Incorrect universe size.
For Arrays over 170 LEDs, it needs to be 510.

Please edit config.yaml and replace 512 with 510 - the configuration editor is currently broken.
